ingress:
  - hostname: utoscan
    service: http://0.0.0.0:3030
  - hostname: ria2
    service: http://0.0.0.0:6800
  - hostname: ocker #portainer
    service: http://0.0.0.0:9000
  - hostname: dcx
    service: http://0.0.0.0:5800
  - hostname: lexget
    service: http://0.0.0.0:5050
  - hostname: etatube
    service: http://0.0.0.0:5050
  - service: http_status:404
